### PR TITLE
Proper parsing of invoice lines

### PR DESCRIPTION
**Pull request by DanielDestino**
The current parser does not take into account that invoice lines can contain newline characters. Instead of using a custom parser for this the inbuilt .NET CSV parser is used.

### CODE REVIEW

**Comment by paulirwin** [comment]
I have had good luck using CsvHelper in the past, have you considered using that? Good for if you want it to have a strong model. http://www.nuget.org/packages/CsvHelper/ and https://github.com/JoshClose/CsvHelper

**Comment by DanielDestino** [comment]
I am thinking that adding a third party library would be unnecessary when there is a inbuilt library that handles it pretty well.

**Comment by paulirwin** [comment]
@DanielDestino I definitely appreciate the concern over adding an external dependency. I would say it would be unnecessary *today*, but TextFieldParser is not portable and is not included in the .NET Core foundational libraries, meaning this code would prevent compilation targeting .NET Core. At some point in the future this will need to be rewritten to use an external portable CSV library like CsvHelper, unless TextFieldParser is added to CoreFX (not likely at this point for RTM).

**Comment by ithielnor** [comment]
I don't have a problem merging this in, but there are some conflicts you need to resolve first.

We can upgrade to another library later if it becomes necessary.

**Comment by DanielDestino** [comment]
Conflicts fixed, please merge :)

**Comment by chris2402** [comment]
This merge solves a problem when parsing an invoice with no itemlines (CsvLineItems == null), which throws an NullPointerException in Invoice.cs line 235

**Pull request merged**
